import { createApp } from 'vue'
import 'normalize.css/normalize.css'
import './assets/css/reset.css'
import App from './App.vue'
// import ElementPlus from 'element-plus'
// import 'element-plus/dist/index.css'
import router from './router'
import pinia from './store'
import './service/modules/home'
createApp(App).use(router).use(pinia).mount('#app')
